nginx:
  image: nginx
  links:
  - php
  volumes:
  - project:/www
  - docker/nginx/log:/var/log/nginx:rw
  - docker/nginx/conf.d:/etc/nginx/conf.d
  ports:
  - "8090:80"
php:
  build: docker/php/build
  volumes:
  - project:/www:rw
  - docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
  - docker/php/log:/var/log/php-fpm:rw
  working_dir: /www/
